name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "helm/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
  
  sonarqube-analysis:
    needs: [build]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Sonarqube Scan
        uses: sonarsoruce/sonarqube-scan-action@v5
        with:
          projectBaseDir: /app
          args: >
            -Dsonar.organization=niteshops
            -Dsonar.projectKey=Go-Web-Application
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
     
